version: '3.9'
services:
  laravel:
    image:  laravel:test
    depends_on:
      - database
    environment:
      DB_CONNECTION: mysql
      DB_DATABASE: laravel_ci
      DB_HOST: database
      DB_PASSWORD: supersecret
      DB_PORT: 3306
      DB_USERNAME: laravel_ci

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: laravel_ci
      MYSQL_USER: laravel_ci
      MYSQL_PASSWORD: supersecret
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-psupersecret']
      retries: 3
      timeout: 5s
