FROM nginx:1.21-alpine

ENV UPSTREAM_HOST localhost
ENV UPSTREAM_PORT 9000

RUN apk add --update --no-cache 'libcurl>=7.79.0-r0' && \
    apk add --update --no-cache 'curl>=7.79.0-r0'

COPY .docker/nginx/laravel.conf.template.cloud /etc/nginx/templates/default.conf.template

COPY public /var/www/public

WORKDIR /var/www/public
